repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-json
  - id: no-commit-to-branch
  - id: mixed-line-ending
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
- hooks:
  - id: actionlint
  repo: https://github.com/rhysd/actionlint/
  rev: v1.7.1
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.27.0
